version: '3.1'
services:
    postgres:
        image: 'postgres:15-alpine'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - POSTGRES_USER=weeek
            - POSTGRES_PASSWORD=weeek
            - POSTGRES_DB=weeek
        ports:
            - '10004:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '10000:80'

    php-fpm:
        build: docker/php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/cli/conf.d/99-overrides.ini'
